import React from 'react';

export const statusLabel = (status) => ({ Approved: 'QC Approved', Rejected: 'QC Rejected', Hold: 'QC Hold', Available: 'Available Stock' })[status] || status;
export const readable = (value) => value.replace(/([A-Z])/g, ' $1').replace(/^./, (char) => char.toUpperCase());
export const formatDate = (value) => value ? new Date(value).toLocaleString() : '—';
export const person = (value) => value?.name || value?.email || value || '—';
export function Status({ value }) { return <span className={`flow-status flow-status-${(value || '').toLowerCase().replaceAll(' ', '-')}`}>{statusLabel(value)}</span>; }
export function Modal({ title, children, onClose, busy }) {
  return <div className="user-modal-backdrop" onMouseDown={() => !busy && onClose()}><section className="flow-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header className="card-heading"><h2>{title}</h2><button className="modal-close" type="button" disabled={busy} onClick={onClose} aria-label="Close">×</button></header>{children}</section></div>;
}
export function Field({ label, type = 'text', value = '', onChange, options = [], required = true, ...props }) {
  return <label className="flow-field">{label}{type === 'select' || type === 'multiselect' ? <select multiple={type === 'multiselect'} value={value} required={required} onChange={(event) => onChange(type === 'multiselect' ? [...event.target.selectedOptions].map((option) => option.value) : event.target.value)} {...props}>{type === 'select' && <option value="">Select {label.toLowerCase()}</option>}{options.map((option) => <option key={option.value ?? option} value={option.value ?? option}>{option.label ?? option}</option>)}</select> : type === 'textarea' ? <textarea value={value} required={required} onChange={(event) => onChange(event.target.value)} {...props} /> : <input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} {...props} />}</label>;
}
export function Documents({ documents = [] }) {
  return <div className="flow-documents">{documents.length ? documents.map((document, index) => <a key={document._id || index} href={document.fileUrl} target="_blank" rel="noreferrer"><strong>{document.kind || 'Supplier document'}</strong><span>{document.fileName || 'Open document'}</span></a>) : <p>No documents uploaded yet.</p>}</div>;
}
export function Pager({ pagination, onPage, loading }) {
  return <div className="pagination"><span>{pagination.total || 0} records · Page {pagination.page || 1} of {Math.max(1, pagination.totalPages || 1)}</span><div><button className="outline" disabled={loading || pagination.page <= 1} onClick={() => onPage(pagination.page - 1)}>Previous</button><button className="outline" disabled={loading || pagination.page >= pagination.totalPages} onClick={() => onPage(pagination.page + 1)}>Next</button></div></div>;
}
export function RecordDetails({ record, raw }) {
  const fields = raw ? ['materialCode', 'materialName', 'materialType', 'supplierName', 'poNumber', 'invoiceNumber', 'batchNo', 'manufacturer', 'receivedQuantity', 'quantityUnit', 'containers', 'manufacturingDate', 'expiryDate', 'receivingDate', 'storageRequirement', 'documentStatus', 'availableQuantity', 'remarks'] : ['materialCode', 'materialName', 'quantity', 'quantityUnit', 'batchNo', 'productionOrder', 'manufacturingDate', 'expiryDate', 'acceptedQuantity', 'availableQuantity', 'location', 'customer', 'salesOrder', 'destination', 'dispatchDate', 'remarks', 'verificationRemarks', 'discrepancyReason'];
  return <><dl className="flow-details">{fields.filter((key) => record[key] !== undefined && record[key] !== '').map((key) => <div key={key}><dt>{readable(key)}</dt><dd>{key.endsWith('Date') ? formatDate(record[key]) : String(record[key])}</dd></div>)}<div><dt>Recorded by</dt><dd>{person(record.receivedBy || record.createdBy)}</dd></div><div><dt>Recorded at</dt><dd>{formatDate(record.createdAt)}</dd></div>{record.verification?.acceptedAt && <><div><dt>Storage location</dt><dd>{record.verification.location}</dd></div><div><dt>Warehouse accepted by</dt><dd>{person(record.verification.acceptedBy)}</dd></div><div><dt>Warehouse accepted at</dt><dd>{formatDate(record.verification.acceptedAt)}</dd></div></>}</dl>
    {record.sourceRequisitions?.length > 0 && <div className="flow-note"><b>Source production requisitions</b><p>{record.sourceRequisitions.map((source) => source.number || source).join(', ')}</p></div>}
    {record.sampling?.number && <section className="flow-section"><h3>Sampling details · {record.sampling.number}</h3><dl className="flow-details"><div><dt>Material</dt><dd>{record.materialName}</dd></div><div><dt>Quantity</dt><dd>{record.sampling.quantity} {record.quantityUnit}</dd></div><div><dt>Containers sampled</dt><dd>{record.sampling.containers}</dd></div><div><dt>Sampled by</dt><dd>{person(record.sampling.sampledBy)}</dd></div><div><dt>Sampling date</dt><dd>{formatDate(record.sampling.samplingDate)}</dd></div><div><dt>Remarks</dt><dd>{record.sampling.remarks || '—'}</dd></div></dl></section>}
    {record.qc?.tests?.length > 0 && <section className="flow-section"><h3>QC test results</h3><div className="table-wrap"><table className="stock-table"><thead><tr>{['Test', 'Specification', 'Limit', 'Actual', 'Method', 'Result', 'Analyst / ID', 'Date', 'Remarks'].map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{record.qc.tests.map((test, index) => <tr key={test._id || index}><td>{test.testName}</td><td>{test.specification}</td><td>{test.requiredLimit}</td><td>{test.actualResult}</td><td>{test.testMethod}</td><td>{test.result}</td><td>{person(test.analyst)}<small>{test.analyst?._id}</small></td><td>{formatDate(test.testDate)}</td><td>{test.remarks}</td></tr>)}</tbody></table></div></section>}
    {record.qc?.decision && <div className="flow-note"><b>QC decision: {statusLabel(record.qc.decision)}</b><p>{record.qc.decisionRemarks}</p><small>{person(record.qc.decisionBy)} · {formatDate(record.qc.decisionAt)}</small></div>}
    {record.statusHistory?.length > 0 && <section className="flow-section"><h3>Receiving & QC history</h3><ol className="flow-timeline">{record.statusHistory.map((entry, index) => <li key={entry._id || index}><b>{entry.from ? statusLabel(entry.from) + ' ? ' : ''}{statusLabel(entry.to)}</b><span>{entry.note}</span><small>{person(entry.changedBy)} ? {formatDate(entry.changedAt)}</small></li>)}</ol></section>}
    {record.issues?.length > 0 && <section className="flow-section"><h3>Dispensing & production receipts</h3><div className="table-wrap"><table className="stock-table"><thead><tr>{['Dispensing', 'Batch / location', 'Issued', 'Actual received', 'Difference', 'Status', 'Reason / resolution', 'User / time'].map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{record.issues.map((issue) => <tr key={issue._id}><td>{issue.number}</td><td>{issue.batchNo}<small>{issue.location}</small></td><td>{issue.quantity}</td><td>{issue.actualQuantity ?? '—'}</td><td>{issue.differenceQuantity ?? '—'}</td><td><Status value={issue.status} /></td><td>{issue.reason || '—'}{issue.resolution && <small>Resolution: {issue.resolution}</small>}</td><td>{person(issue.dispensedBy)}<small>{formatDate(issue.dispensedAt)}</small>{issue.receivedAt && <small>Received: {person(issue.receivedBy)} · {formatDate(issue.receivedAt)}</small>}</td></tr>)}</tbody></table></div></section>}
  </>;
}
